---

- name: Create node_exporter directory
  file:
    path: "{{ node_exporter_dir_path }}"
    state: directory
    mode: "0755"

- name: Create docker-compose.yml from template
  template:
    src: "{{ docker_compose_template }}"
    dest: "{{ node_exporter_dir_path }}/docker-compose.yml"

- name: Create and start Node-exporter
  community.docker.docker_compose_v2:
    project_src: "{{ node_exporter_dir_path }}"
    state: present
    recreate: always
    pull: always