---

- name: Ensure letsencrypt dir exists
  file:
    path: "{{ letsencrypt_path }}"
    state: directory
    mode: '0755'
  become: true

- name: Deploy Cloudflare API token for Certbot
  copy:
    dest: "{{ cloudflare_credentials_path }}"
    content: |
      dns_cloudflare_api_token = {{ cloudflare_api_token }}
    owner: root
    group: root
    mode: '0600'
  become: true
