---

- name: Ensure certbot renews certificates automatically
  cron:
    name: "Renew Let's Encrypt certificates"
    minute: "0"
    hour: "3"
    job: "/usr/bin/certbot renew --quiet"
    state: present