---

apiVersion: v1
kind: Service
metadata:
  name: novapress-db
spec:
  type: ClusterIP
  selector:
    app: novapress-db
  ports:
    - port: {{ .Values.db.port }}
      targetPort: {{ .Values.db.port }}