apiVersion: v1
kind: Service
metadata:
  name: novapress-front
spec:
  type: ClusterIP
  selector:
    app: novapress-front
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
